version: '1.0'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    container_name: zookeeper
    volumes:
      - ./zoo_volume/data:/var/lib/zookeeper/data
      - ./zoo_volume/log:/var/lib/zookeeper/log

  broker01:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    container_name: broker01
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT_HOST://broker01:9092,PLAINTEXT://broker01:9093,PLAINTEXT_BROKER://broker01:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://broker01:9092,PLAINTEXT://broker01:9093,PLAINTEXT_BROKER://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_BROKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
    ports:
      - 9092:9092
      - 9094:9094
    volumes:
      - ./kafka_volume/data:/var/lib/kafka/data

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - broker01
    environment:
      KAFKA_CLUSTERS_0_NAME: my-kafka-ui
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker01:9093

  my-schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: my-schema-registry
    container_name: my-schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "broker01:9093"
      SCHEMA_REGISTRY_HOST_NAME: my-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://localhost:8081,http://my-schema-registry:8081
    depends_on:
      - broker01

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: casZtRGKHRJx69EqUghvvgEvjnaLjFEB
    ports:
      - 8443:8443
    volumes:
      - ./hadoop_config:/opt/hadoop_config # Mount Hadoop configuration files
    depends_on:
      - broker01

  namenode:
    image: apache/hadoop:3
    hostname: namenode
    command: [ "hdfs", "namenode" ]
    ports:
      - 9870:9870
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
  datanode:
    image: apache/hadoop:3
    command: [ "hdfs", "datanode" ]
    env_file:
      - ./config
  resourcemanager:
    image: apache/hadoop:3
    hostname: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    ports:
      - 8088:8088
    env_file:
      - ./config
  nodemanager:
    image: apache/hadoop:3
    command: [ "yarn", "nodemanager" ]
    env_file:
      - ./config
